# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [34]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [35]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [36]:
print(np.__version__)
print(np.show_config())

1.21.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/steffyantidwie/opt/anaconda3/envs/DA_environment/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/steffyantidwie/opt/anaconda3/envs/DA_environment/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/steffyantidwie/opt/anaconda3/envs/DA_environment/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/steffyantidwie/opt/anaconda3/envs/DA_environment/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/steffyantidwie/opt/anaconda3/envs/DA_environment/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/steffyantidwie/opt/anaconda3/envs/DA_environment/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/steffyantidwie/opt/anaconda3/envs/DA_envi

#### 3. Create a null vector of size 10 (★☆☆)

In [37]:
z = np.zeros(10)
print (z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [38]:
x = np.array([1,2,3,4])
#size of the array
x.size

#Memory size of one array element in bytes
x.itemsize

#memory size of any array
print (x.size * x.itemsize)

32


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

python -c "import numpy; numpy.info(numpy.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [39]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [40]:
print (np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [41]:
x = np.arange(10,50)
print (x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [42]:
print (np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [43]:
print (np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [44]:
print (np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [45]:
x = np.random.random((3,3,3))
x

array([[[0.62832673, 0.13660424, 0.04112303],
        [0.85438104, 0.24291822, 0.72352161],
        [0.87245364, 0.75571732, 0.50505291]],

       [[0.25324081, 0.45304645, 0.36829228],
        [0.02526413, 0.66997234, 0.9911559 ],
        [0.57096209, 0.78471164, 0.62638785]],

       [[0.94130141, 0.17405401, 0.5379227 ],
        [0.19806657, 0.67400747, 0.33690735],
        [0.70311948, 0.32471689, 0.28242057]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [46]:
x = np.random.random((10,10))
x_min, x_max = x.min(), x.max()

print (x_min)
print (x_max)

0.018605309109809842
0.980332091823868


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [47]:
x = np.random.random(30)
m = x.mean()

print (m)

0.4989299403320679


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [67]:
x = np.ones((5,5), dtype=int)
x[1:-1,1:-1]=0
print (x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [63]:
x = np.ones((2,2), dtype=int)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)

print (x)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [50]:
print (0 * np.nan)
print (np.nan == np.nan)
print (np.inf > np.nan)
print (np.nan - np.nan)
print (np.nan in set([np.nan]))
print (0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [51]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [64]:
x = np.zeros ((8,8), dtype =int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1

print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [53]:
x= np.unravel_index(100, (6,7,8))
print (x)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [54]:
array= np.array([[0,1], [1,0]])
x = np.tile(array,(4,4))
print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [55]:
x = np.random.random((5,5))
x = (x-np.mean(x))/(np.std(x))
print (x)

[[ 0.72583581  1.52115293  1.94741094 -1.10061345  0.85056112]
 [-1.69717332  0.83974171  1.29252141 -0.29304888 -0.67568405]
 [-0.45210872  0.37951594  0.15352557 -0.77473698 -0.74066821]
 [ 0.51983606 -0.03751936 -1.56507844 -0.0645278  -0.46318336]
 [-1.24214233 -0.2443741  -1.21825094  0.75083546  1.58817301]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [56]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [70]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [62]:
Z = np.arange(11)
Z[(Z>3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [65]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [97]:
print (np.array(0) / np.array(0))
print (np.array(0) // np.array(0))
print (np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/6h/fzl81hw55yj1kpvb9rwhd7wr0000gn/T/ipykernel_89328/1773308525.py:1: RuntimeWarning: invalid value encountered in true_divide
  print (np.array(0) / np.array(0))
/var/folders/6h/fzl81hw55yj1kpvb9rwhd7wr0000gn/T/ipykernel_89328/1773308525.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print (np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

np.intersect1d(array1, array2)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [72]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/6h/fzl81hw55yj1kpvb9rwhd7wr0000gn/T/ipykernel_89328/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [76]:
today = np.datetime64 ('today', 'D')
tomorrow = today + np.timedelta64(1,'D')
yesterday = today - np.timedelta64 (1,'D')

print (today)
print (tomorrow)
print (yesterday)

2021-10-21
2021-10-22
2021-10-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [78]:
print("July, 2016")
np.arange('2016-06', '2016-07', dtype='datetime64[D]')

July, 2016


array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1

B = np.ones(3)*2

C = np.ones(3)*3

np.add(A,B,out=B)

np.divide(A,2,out=A)

np.negative(A,out=A)

np.multiply(A,B,out=A)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [80]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [93]:
def generate():
   for n in range(10):
       yield n
nums = np.fromiter(generate(),dtype=float,count=-1)
print("New array:", nums)

New array: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [81]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [82]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.2329331  0.25315285 0.2734627  0.43417994 0.65292627 0.73149208
 0.80490795 0.8262319  0.83275551 0.89197899]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [83]:
A = np.random.randint(0,3,7)
B = np.random.randint(0,3,7)
equal = np.allclose(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [84]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [85]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.0713329  0.64253623 0.48368126 0.72939402 0.37035516 0.7930131
 0.30204617 0.86043268 0.92003344 1.12545644]
[0.96031257 0.24017325 0.0611062  0.25945784 1.33997853 0.81760522
 0.92979969 0.63015236 0.89052055 0.50517949]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [86]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.00380025 0.31969401 0.63829624 0.74616674 0.20352187 0.0820253
 0.77388841 0.03175498 0.         0.36971787]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [88]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [90]:
np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [98]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/var/folders/6h/fzl81hw55yj1kpvb9rwhd7wr0000gn/T/ipykernel_89328/3803083766.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [91]:
Z = np.genfromtxt("missing.dat", delimiter=",")

OSError: missing.dat not found.

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)